### ISSUE TITLE
ImportError: No module named sigmf_swig

### ISSUE THREAD

**Issue by ctriant** [skysafe/gr-sigmf#15]
Hello,

I'm trying to use your gr-sigmf implementation, but even if I managed to build it successfully I get the well-known "No module named sigmf_swig" error when I try to run the sigmf-sink example.

Searching a bit on the code I found some potential problems like unimplemented functions. However still no hope. Could you please give me some info about your working setup?

I run it on the latest openSuse Tumbleweed 4.17.3-1.

Thanks in advance.

**Comment by ctriant** [comment]
Just found out that I didn't pay much attention on the cmake output.

`Could NOT find PythonLibs (missing: PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS) (Required is at least version "2")
`

However, in my defense the cmake output was indicating successful build.


`Configuring done
-- Generating done
-- Build files have been written to: /home/ctriant/projects/gr-sigmf/build
`

**Comment by pwicks86** [comment]
Ah, yeah I see. This looks to be caused by the logic in the CMakeLists.txt file in the swig folder. This is pretty much just the default CMakeLists.txt for any OOT created by gr_modtool. That said, it's an open question how useful gr-sigmf is as just a c++ library with no python components.
