### ISSUE TITLE
how to add the annotation to sigmf-meta file

### ISSUE THREAD

**Issue by shawabka** [skysafe/gr-sigmf#17]
Hi,

how you can add the capture and the annotation fields to the sigmf-meta file? is there any example to add these fields.

thanks,

**Comment by pwicks86** [comment]
The sink block should create an initial capture segment for the file and if it receives any stream tags that it knows should correspond to new capture segments (i.e. any of the tags from uhd blocks) then it should create those as well. As far as annotations, if the sink block receives any other stream tags, it will attempt convert them into annotations for the current file. If either of those things doesn't happen, then it's probably a bug in gr-sigmf and should be addressed. 

Apart from that, you can always edit the metadata file after the fact to add any other relevant annotations for a given recording.
