### ISSUE TITLE
Update gr-sigmf to be compatible with gnuradio 3.8

### ISSUE THREAD

**Issue by catemarie** [skysafe/gr-sigmf#21]
We will probably need to convert the grc files to yml, may also require changes to cmake.
gr_modtool is not even up to date yet, however.

**Comment by WenqingYan** [comment]
Wanna ask which branch is compatible gnuradio3.8 now. I tried master branch but not working. Still require version 3.7.2.

**Comment by storborg** [comment]
The `maint-3.8` branch is compatible with 3.8 now. The `master` branch is compatible with 3.9 and (as of this comment) master. The plan is to branch a `maint-3.9` branch at some point in the future, prior to introducing any breaking changes that are newer than GR 3.9.
