### ISSUE TITLE
Namespace Conflict with Official SigMF

### ISSUE THREAD

**Issue by Teque5** [skysafe/gr-sigmf#25]
A few of us are working on additions to the official [SigMF python package](https://github.com/gnuradio/SigMF).

We also use `gr-sigmf` and the namespace conflict for `import sigmf` yeilds :frowning:, since both this package and the official installer use `sigmf`.

I know changing namespace in GNU Radio modules is a pain, but we think that the official sigmf repo shouldn't have to change.

**Comment by pwicks86** [comment]
`gr-sigmf-io` works for me.

**Comment by pwicks86** [comment]
We ended up going with `gr_sigmf`. See d03774a1328a2217b5ddd3fdde2419c1c8cf241e

**Comment by Teque5** [comment]
I tested d03774a and it works in python2 interpreter, but grc is still trying to `import sigmf` instead of `import gr_sigmf` when I use a `SigMF Source` block.

**Comment by pwicks86** [comment]
Ah, oops.. thanks for trying it out. I'll fix that momentarily.

**Comment by pwicks86** [comment]
Should be fixed now.

**Comment by Teque5** [comment]
Yup; looks good, closing issue. Thanks folks.
